name: Send CVE Reports to Jira

description: Uploads vulnerability scan reports to Jira

inputs:
  reports:
    description: "Comma-separated list of SARIF report file paths"
    required: true
  jira-url:
    description: "Jira webhook URL"
    required: true
  jira-auth-token:
    description: "Jira authentication token"
    required: true
  minimum-level:
    description: "Minimum severity level to report"
    required: false
    default: "MEDIUM"

runs:
  using: "composite"
  steps:
    - name: Checkout k8s-workflows repository
      uses: actions/checkout@v4
      with:
        repository: "canonical/k8s-workflows"
        path: "k8s-workflows"

    - name: Send vulnerability records
      shell: bash
      run: |
        IFS=',' read -ra REPORTS <<< "${{ inputs.reports }}"
        for report in "${REPORTS[@]}"; do
          ./k8s-workflows/scripts/cve-reports/send-scan.py --report-path="$report" \
            --jira-url="${{ inputs.jira-url }}" \
            --jira-auth-token="${{ inputs.jira-auth-token }}" \
            --add-github-meta --minimum-level="${{ inputs.minimum-level }}" --verbose
        done
