name: Lint and Test on Pull Request

on:
  pull_request:

jobs:
  lint-and-unit-tests:
    name: Lint Code and Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.10"
      - run: pip install tox
      - run: tox -e lint
      - run: tox -e unit
