# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Workflow Self-Test (Rockcraft Cache)

on:
  pull_request:
  
jobs:
  save-cache:
    uses: ./.github/workflows/build_rocks.yaml
    secrets: inherit
    with:
      working-directory: "tests/workflows/rock/"
      cache-action: save

  restore-cache:
    needs: [ save-cache ]
    uses: ./.github/workflows/build_rocks.yaml
    secrets: inherit
    with:
      working-directory: "tests/workflows/rock/"
      cache-action: restore

